config:
  target: 'https://mcwyczm9qa.execute-api.us-east-1.amazonaws.com/prod'
  phases:
    - duration: 60
      arrivalRate: 10
  defaults:
    headers:
      Content-Type: "application/json"
      x-api-key: "E0xB36XpTdJCz7zMk5rz9ccPMW9mf66abdLxOq2e"
  processor: "./payloadGenerator.js"

scenarios:
  - flow:
    - function: "generatePayload"
    - post:
        url: "/"
        json:
          text: "{{ text }}"

#processors:
#  generatePayload: "./payloadGenerator.js"