config:
  target: 'https://xd04d47wz1.execute-api.us-east-1.amazonaws.com/dev'
  phases:
    - duration: 600
      arrivalRate: 5
  defaults:
    headers:
      Content-Type: "application/json"
      x-api-key: "rxEsARo3LU2CKBslMyFHF3X0OfBzDPvd2QzbW7Zi"
  processor: "./payloadGenerator.js"

scenarios:
  - flow:
    - function: "generatePayload"
    - post:
        url: "/"
        json:
          text: "{{ text }}"

#processors:
#  generatePayload: "./payloadGenerator.js"
